version: "3"
services:
  django:
    build: .
    container_name: django
    env_file:
      - .env
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/usr/src/app/static
    restart: always
    depends_on:
      - postgres


  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: '${PG_DATABASE}'
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - static_volume:/usr/src/app/static
    depends_on:
      - django


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email denis.lukianov1801@gmail.com -d 34.16.146.16 --agree-tos

volumes:
  static_volume:
  postgres-data:
