version: "3"
services:
  django:
    build: .
    container_name: django
    env_file:
      - .env
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/usr/src/app/static
    restart: always
    depends_on:
      - postgres
   
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: '${PG_DATABASE}'
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data



  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
    depends_on:
      - django

volumes:
  static_volume:
  postgres-data:
