# Generated by Django 4.2.7 on 2023-12-02 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breaks', '0002_alter_organization_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='organization_employees', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('min_active', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Минимальное количество активных сотрудников')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Начало Обеда')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Конец Обеда')),
                ('break_max_duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Максимальное длительность обеда')),
                ('employees', models.ManyToManyField(blank=True, related_name='group_employees', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='group_managers', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='breaks.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
    ]
