# Generated by Django 4.2.7 on 2023-12-03 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0003_alter_organization_employees_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='groups', to='breaks.organization', verbose_name='Организация'),
        ),
    ]
