# Generated by Django 4.2.7 on 2023-12-03 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0004_alter_group_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата смены')),
                ('breaks_start', models.TimeField(verbose_name='Начало обеда')),
                ('breaks_end', models.TimeField(verbose_name='Конец обеда')),
                ('breaks_max_duration', models.IntegerField(verbose_name='Макс. продолжительность обеда')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='breaks.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ('-date',),
            },
        ),
    ]
