# Generated by Django 4.2.7 on 2023-12-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0009_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность обеда'),
        ),
    ]
